name: login
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0
  image_picker: "^0.4.5"
  rocket_chat_dart: ^0.0.38

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/profile.jpg
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf